version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: transcendence_db
      POSTGRES_USER: transcendence_user
      POSTGRES_PASSWORD: yourpassword

  web:
    build: ./Django
    command: gunicorn --bind 0.0.0.0:8000 transcendence.wsgi:application
    volumes:
      - ./Django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
